spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
        url: jdbc:mariadb://qqer.synology.me:8090/test
        username: root
        password: eastcost21
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:          pool-name: hikari-cp
          maximum-pool-size: 10
          minimum-idle: 2
          data-source-properties:            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
Configuration:
  name: Default
  Properties:
    Property:
      name: log-path
      value: "logs"
  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
    File:
      name: File_Appender
      fileName: ${log-path}/logfile.log
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  Loggers:
      Root:
        level: debug
        AppenderRef:
          - ref: Console_Appender
      Logger:
        - name: com.spring.boot.api.apiservice
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: error   
server:
  port: 8000