spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
        url: jdbc:mariadb://qqer.synology.me:8090/test
        username: root
        password: eastcost21
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:          pool-name: hikari-cp
          maximum-pool-size: 10
          minimum-idle: 2
          data-source-properties:            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8000
